[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
hello_bonsol_tutorial = "AL2sWHZ42EymvGFLDHszdDwsXqBtxTg1wWhc4wesQEku"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
